WIP: Integrate Rust extension into repository
The dist scripts now generate 4 packages:

neo4j
Contains the driver with extensions, but falls back to pure Python
implementation if not wheel is available and compilation from source fails.
wheels + sdist are built.

neo4j-py
Pure Python implementation (like neo4j was before).
Python wheel + sdist are built.

neo4j-rust-ext
Enforces the existence of the Rust extensions. Else, the installation fails.
wheels + sdist are built.

neo4j-driver
The legacy driver alias. It's now the same as neo4j-py, except that:
only sdist is built.

diff --git a/bin/dist-functions b/bin/dist-functions
--- a/bin/dist-functions
+++ b/bin/dist-functions
@@ -1,32 +1,78 @@
 #!/usr/bin/env bash
 set -e
 
-ROOT=$(dirname "$0")/..
+ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/.."
 SRC="${ROOT}/src"
-DIST="${ROOT}/dist"
+DIST_FOLDER="dist"
+DIST="${ROOT}/${DIST_FOLDER}"
+DIST_FILES=()
 
-function get_package
-{
+function load_dist_files {
+    local VERSION
+    VERSION="$1"; shift
+    mapfile -td '' DIST_FILES < <(find "$DIST" -regex '^.*/\(neo4j\|neo4j-driver\|neo4j_driver\|neo4j-py\|neo4j_py\|neo4j-rust-ext\|neo4j_rust_ext\)-'"${VERSION}"'\(-.+\)?\.\(whl\|tar\.gz\)$' -print0)
+}
+
+function sed_extract {
+    local PATTERN FILE OUT MATCHES
+    PATTERN="${1////\\/}"; shift
+    FILE="$1"; shift
+    OUT="$1"; shift
+    MATCHES=$(sed -n "s/^${PATTERN}/\1/p" "$FILE")
+    if [ "$(echo "$MATCHES" | wc -l)" -ne 1 ]; then
+        echo "Error: Expected exactly one match for pattern '${PATTERN}' in file '${FILE}'."
+        echo "Found $(echo "$MATCHES" | wc -l) matches."
+        return 1
+    fi
+    eval "$OUT="'"'"$MATCHES"'"'
+    return 0
+}
+
+function sed_replace {
+    local PATTERN REPLACEMENT FILE MATCHES FORCE
+    PATTERN="${1////\\/}"; shift
+    REPLACEMENT="${1////\\/}"; shift
+    FILE="$1"; shift
+    MATCHES="$(sed -i "s/${PATTERN}/${REPLACEMENT}/g w /dev/stdout" "${FILE}" | wc -l)"
+    if [ "$1" = "--force" ] || [ "$1" = "-f" ]; then
+        FORCE=1
+        shift
+    fi
+    if [ -n "$FORCE" ]; then
+        return 0
+    fi
+    if [ "${MATCHES}" -eq 0 ]; then
+        echo "Error: No matches found for pattern '${PATTERN}' in file '${FILE}'"
+        return 1
+    fi
+}
+
+function get_package {
     cd "${SRC}"
     python -c "from neo4j._meta import package; print(package)"
     cd - > /dev/null
 }
 
-function set_package
-{
-    sed -i 's/^package = .*/package = "'$1'"/g' "${SRC}/neo4j/_meta.py"
+function set_package {
+    local VALUE
+    VALUE="$1"; shift
+    sed_replace '^\(package\s*=\s*"\).*\("  # \[script-set\]$\)' '\1'"$VALUE"'\2' "${SRC}/neo4j/_meta.py" "$@"
+    sed_replace '^\(name\s*=\s*"\).*\("  # \[script-set\]$\)' '\1'"$VALUE"'\2' "${ROOT}/pyproject.toml" "$@"
 }
 
-function get_version
-{
+function get_version {
     cd "${SRC}"
     python -c "from neo4j._meta import version; print(version)"
     cd - > /dev/null
 }
 
-function set_version
-{
-    sed -i 's/^version = .*/version = "'$1'"/g' "${SRC}/neo4j/_meta.py"
+res=$(sed -n 's/^version\s*=\s*"\(.*\)"  # \[script-set\]$/\1/p' "src/neo4j/_meta.py")
+
+function set_version {
+    local VALUE
+    VALUE="$1"; shift
+    sed_replace '^\(version\s*=\s*"\).*\("  # \[script-set\]$\)' '\1'"$VALUE"'\2' "${SRC}/neo4j/_meta.py" "$@"
+    sed_replace '^\(version\s*=\s*"\).*\("  # \[script-set\]$\)' '\1'"$VALUE"'\2' "${ROOT}/pyproject.toml" "$@"
 }
 
 function get_deprecated {
@@ -36,59 +82,134 @@ function get_deprecated {
 }
 
 function set_deprecated {
-    sed -i 's/^deprecated_package = .*/deprecated_package = '$1'/g' "${SRC}/neo4j/_meta.py"
+    local VALUE
+    VALUE="$1"; shift
+    sed_replace '^\(deprecated_package\s*=\s*\).*\(  # \[script-set\]$\)' '\1'"$VALUE"'\2' "${SRC}/neo4j/_meta.py" "$@"
 }
 
-# distribution normalization according to PEP 625 https://peps.python.org/pep-0625/
-function normalize_dist_name
-{
-    echo $1 | sed 's/[._-]\+/_/g' | tr '[:upper:]' '[:lower:]'
-}
+function check_file {
+    echo -n "Checking dist file '$1' ... "
 
-function check_file
-{
-    FILE=$1
-    echo -n "Checking file $(basename "${FILE}")... "
-    if [ -f "${FILE}" ]
-    then
-        echo "OK"
+    OLD_IFS="$IFS"
+    function cleanup {
+        IFS="$OLD_IFS"
+    }
+    IFS=
+    trap cleanup EXIT
+
+    FILES=($1)
+
+    trap - EXIT
+    cleanup
+
+    if [ "${#FILES[@]}" != "1" ]; then
+        echo "Error: Expected exactly one file, found ${#FILES[@]}:"
+        for FILE in "${FILES[@]}"; do
+            echo "  '$FILE'"
+        done
+        return 1
+    fi
+
+    if [ -f "${FILES[0]}" ]; then
+        echo "OK: Found '${FILES[0]}'"
         return 0
     else
-        echo "missing"
+        echo "Missing"
         return 1
     fi
 }
 
-function set_metadata_and_setup
-{
-    PACKAGE="$1"; shift
-    DEPRECATED="$1"; shift
-    VERSION="$1"; shift
+function set_metadata_and_setup {
+    local DEPRECATED="False"
+    local SDIST
+    local WHEEL
+    local MATURIN_WHEEL
+    local CROSS
+    local DOCKER_PRUNE
+    local PWD
+    PWD="$ROOT"
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+            --deprecated)
+                DEPRECATED="True"
+                shift
+                ;;
+            --sdist)
+                SDIST=1
+                shift
+                ;;
+            --wheel)
+                WHEEL=1
+                shift
+                ;;
+            --wheel-maturin)
+                MATURIN_WHEEL=1
+                shift
+                ;;
+            --cross)
+                CROSS=1
+                shift
+                ;;
+            --docker-prune)
+                DOCKER_PRUNE=1
+                shift
+                ;;
+            --pwd)
+                PWD="$2"
+                shift
+                shift
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+
+    if [ $((${WHEEL:-0} + ${MATURIN_WHEEL:-0} + ${CROSS:-0})) -gt 1 ]; then
+        echo "Choose at most one of --wheel, --wheel-maturin or --cross"
+        return 1
+    fi
+
+    local PACKAGE="$1"; shift
+    local VERSION="$1"; shift
 
     cd "${ROOT}"
 
     # Capture original package metadata
+    local ORIGINAL_PACKAGE
     ORIGINAL_PACKAGE=$(get_package)
+    local ORIGINAL_VERSION
     ORIGINAL_VERSION=$(get_version)
+    local ORIGINAL_DEPRECATED
     ORIGINAL_DEPRECATED=$(get_deprecated)
     echo "Source code originally configured for package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}/deprecated=${ORIGINAL_DEPRECATED}"
     echo "----------------------------------------"
-    grep "package\s\+=" "${SRC}/neo4j/_meta.py"
-    grep "version\s\+=" "${SRC}/neo4j/_meta.py"
-    grep "deprecated_package\s\+=" "${SRC}/neo4j/_meta.py"
+    echo "_meta.py:"
+    grep "  # \[script-set\]" "${SRC}/neo4j/_meta.py"
+    echo ""
+    echo "pyproject.toml:"
+    grep "  # \[script-set\]" "${ROOT}/pyproject.toml"
+    grep "# \[rust_ext\]" "${ROOT}/pyproject.toml"
+    echo ""
+    echo "MANIFEST.in:"
+    grep "# \[rust_ext\]" "${ROOT}/MANIFEST.in"
     echo "----------------------------------------"
+    echo ""
 
     function cleanup() {
-      # Reset to original package metadata
-      set_package "${ORIGINAL_PACKAGE}"
-      set_version "${ORIGINAL_VERSION}"
-      set_deprecated "${ORIGINAL_DEPRECATED}"
-      echo "Source code reconfigured back to original package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}/deprecated=${ORIGINAL_DEPRECATED}"
-      echo "----------------------------------------"
-      grep "package\s\+=" "${SRC}/neo4j/_meta.py"
-      grep "version\s\+=" "${SRC}/neo4j/_meta.py"
-      grep "deprecated_package\s\+=" "${SRC}/neo4j/_meta.py"
-      echo "----------------------------------------"
+        cd "${ROOT}"
+        # Reset to original package metadata
+        set_package "${ORIGINAL_PACKAGE}" --force
+        set_version "${ORIGINAL_VERSION}" --force
+        set_deprecated "${ORIGINAL_DEPRECATED}" --force
+        echo "Source code reconfigured back to original package ${ORIGINAL_PACKAGE}/${ORIGINAL_VERSION}/deprecated=${ORIGINAL_DEPRECATED}"
+        echo "----------------------------------------"
+        echo "_meta.py:"
+        grep "  # \[script-set\]" "${SRC}/neo4j/_meta.py"
+        echo ""
+        echo "pyproject.toml:"
+        grep "  # \[script-set\]" "${ROOT}/pyproject.toml"
+        echo "----------------------------------------"
     }
     trap cleanup EXIT
 
@@ -98,29 +219,122 @@ function set_metadata_and_setup
     set_deprecated "${DEPRECATED}"
     echo "Source code reconfigured for package ${PACKAGE}/${VERSION}/deprecated=${DEPRECATED}"
     echo "----------------------------------------"
-    grep "package\s\+=" "${SRC}/neo4j/_meta.py"
-    grep "version\s\+=" "${SRC}/neo4j/_meta.py"
-    grep "deprecated_package\s\+=" "${SRC}/neo4j/_meta.py"
+    echo "_meta.py:"
+    grep "  # \[script-set\]" "${SRC}/neo4j/_meta.py"
+    echo ""
+    echo "pyproject.toml:"
+    grep "  # \[script-set\]" "${ROOT}/pyproject.toml"
     echo "----------------------------------------"
+    echo ""
 
-    # Create source distribution
-    find . -name *.pyc -delete
+    find . -name "*.pyc" -delete
     rm -rf "${SRC}/*.egg-info" 2> /dev/null
-    python -m build $*
-    NORMALIZED_PACKAGE="$(normalize_dist_name $PACKAGE)"
-    if ! (check_file "${DIST}/${NORMALIZED_PACKAGE}-${VERSION}.tar.gz" \
-          || check_file "${DIST}/${PACKAGE}-${VERSION}.tar.gz"); then
-        STATUS=1
+
+    # source distribution (sdist) build
+    if [ -n "${SDIST}" ]; then
+        python -m build --sdist
+    fi
+
+    if [ -n "${CROSS}" ]; then
+        echo "----------------------------------------"
+        echo "Compiling for windows and macOS (docker image ubuntu:22.04)"
+        docker run --rm -v "$ROOT:/io" -w /io -i -a stdout -a stderr ubuntu:22.04 bash << EOF1
+set -ex
+
+apt-get update -q
+apt-get install -yq sudo llvm python3 python3-pip mingw-w64 curl
+pip install -U pip
+pip install maturin[zig]
+
+groupadd --non-unique -g $(id -g) docker
+useradd --create-home --non-unique -u $(id -u) -g $(id -g) docker
+adduser docker sudo
+
+sudo -u docker bash -ex << "EOF2"
+
+export RUSTUP_HOME="\$HOME/.rustup"
+export CARGO_HOME="\$HOME/.cargo"
+curl --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
+export PATH="\$HOME/.cargo/bin:\$PATH"
+rustup target add x86_64-pc-windows-gnu i686-pc-windows-gnu aarch64-pc-windows-msvc x86_64-apple-darwin aarch64-apple-darwin
+
+cd /io
+for python in python3.7 python3.8 python3.9 python3.10 python3.11 python3.12; do
+    maturin build --out "$DIST_FOLDER" --release --interpreter "\$python" --target x86_64-pc-windows-gnu
+    maturin build --out "$DIST_FOLDER" --release --interpreter "\$python" --target i686-pc-windows-gnu
+    maturin build --out "$DIST_FOLDER" --release --interpreter "\$python" --target aarch64-pc-windows-msvc
+    maturin build --out "$DIST_FOLDER" --release --zig --interpreter "\$python" --target x86_64-apple-darwin
+    maturin build --out "$DIST_FOLDER" --release --zig --interpreter "\$python" --target aarch64-apple-darwin
+done
+
+EOF2
+EOF1
+        if [ -n "${DOCKER_PRUNE}" ]; then
+            docker rmi ubuntu:22.04  || true
+        fi
+        echo "----------------------------------------"
+        echo ""
+        local TUPLE
+        for TUPLE in x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-unknown-linux-musl armv7-unknown-linux-gnueabihf; do
+            local IMAGE
+            case "${TUPLE}" in
+                x86_64-unknown-linux-gnu)
+                    IMAGE="ghcr.io/rust-cross/manylinux2014-cross:x86_64"
+                    ;;
+                aarch64-unknown-linux-gnu)
+                    IMAGE="ghcr.io/rust-cross/manylinux2014-cross:aarch64"
+                    ;;
+                x86_64-unknown-linux-musl)
+                    IMAGE="ghcr.io/rust-cross/musllinux_1_2-cross:x86_64"
+                    ;;
+                armv7-unknown-linux-gnueabihf)
+                    IMAGE="ghcr.io/rust-cross/manylinux2014-cross:armv7"
+                    ;;
+            esac
+
+            echo "----------------------------------------"
+            echo "Compiling for manylinux ${TUPLE} (docker image ${IMAGE})"
+            docker run --rm -v "$ROOT:/io" -w /io -i -a stdout -a stderr "${IMAGE}" bash << EOF1
+set -ex
+
+pip install -U pip
+pip install maturin
+
+groupadd --non-unique -g $(id -g) docker
+useradd --create-home --non-unique -u $(id -u) -g $(id -g) docker
+adduser docker sudo
+
+sudo -EH -u docker bash -ex << EOF2
+
+export PATH="\\\$PATH:\$PATH"
+export RUSTUP_HOME="\\\$HOME/.rustup"
+export CARGO_HOME="\\\$HOME/.cargo"
+curl --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --target $TUPLE --profile minimal
+export PATH="\\\$CARGO_HOME/bin:\\\$PATH"
+
+export PATH="\\\$PATH:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/python/cp39-cp39/bin:/opt/python/cp310-cp310/bin:/opt/python/cp311-cp311/bin:/opt/python/cp312-cp312/bin"
+
+cd /io
+for python in python3.7 python3.8 python3.9 python3.10 python3.11 python3.12; do
+    maturin build --out "$DIST_FOLDER" --release --interpreter "\\\$python" --target $TUPLE
+done
+
+EOF2
+EOF1
+            if [ -n "${DOCKER_PRUNE}" ]; then
+                docker rmi "${IMAGE}"  || true
+            fi
+            echo "----------------------------------------"
+            echo ""
+        done
+    elif [ -n "${MATURIN_WHEEL}" ]; then
+        # native wheel build using maturin
+        maturin build --out "$DIST_FOLDER" --release
+    elif [ -n "${WHEEL}" ]; then
+        # native wheel build using default build backend
+        python -m build --wheel
     fi
 
     trap - EXIT
     cleanup
-}
-
-function setup
-{
-    ARGS="$*"
-    rm -rf ${DIST} 2> /dev/null
-    set_metadata_and_setup "neo4j-driver" "True" ${ARGS} --sdist  # Legacy package; can be removed in 2.0
-    set_metadata_and_setup "neo4j" "False" ${ARGS}
 }
diff --git a/bin/make-dist b/bin/make-dist
--- a/bin/make-dist
+++ b/bin/make-dist
@@ -1,15 +1,109 @@
 #!/usr/bin/env bash
 set -e
 
-ROOT=$(dirname "$0")/..
-SCRIPT=$(basename "$0")
+ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/.."
+SCRIPT="$(basename "${BASH_SOURCE[0]}")"
+
+function help {
+    echo "usage: ${SCRIPT} [options] VERSION"
+    echo ""
+    echo "options:"
+    echo "  --clean           Clean dist directory before building"
+    echo "  --sdist           Build source distribution"
+    echo "  --wheel           Build wheel distribution"
+    echo "  --cross           Cross compile wheels (implies --wheel)"
+    echo "  --docker-prune    Prune docker images between cross compilations"
+    echo ""
+    echo "Exactly one of --sdist or --wheel must be specified."
+}
+
+SETUP_ARGS=()
+PY_SETUP_ARGS=()
+DIST_TYPES=0
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        --clean)
+            CLEAN=1
+            shift
+            ;;
+        --sdist)
+            SDIST=1
+            SETUP_ARGS+=(--sdist)
+            PY_SETUP_ARGS+=(--sdist)
+            shift
+            DIST_TYPES=$((DIST_TYPES + 1))
+            ;;
+        --wheel)
+            WHEEL=1
+            shift
+            DIST_TYPES=$((DIST_TYPES + 1))
+            ;;
+        --cross)
+            CROSS=1
+            shift
+            DIST_TYPES=$((DIST_TYPES + 1))
+            ;;
+         --docker-prune)
+            SETUP_ARGS+=(--docker-prune)
+            shift
+            ;;
+        -h|--help)
+            help
+            exit 0
+            ;;
+        -*)
+            echo "Unknown option: $1"
+            echo ""
+            help
+            exit 1
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
+if [ -n "$CROSS" ]; then
+    SETUP_ARGS+=(--cross)
+    PY_SETUP_ARGS+=(--wheel)
+elif [ -n "$WHEEL" ]; then
+    SETUP_ARGS+=(--maturin-wheel)
+    PY_SETUP_ARGS+=(--wheel)
+fi
 
 VERSION="$1"
-if [ "${VERSION}" == "" ]
-then
-    echo "usage: ${SCRIPT} VERSION"
+shift
+
+if [ -n "$1" ]; then
+    echo "Too many arguments"
+    echo ""
+    help
     exit 1
-else
-    source "${ROOT}/bin/dist-functions"
-    setup "${VERSION}"
 fi
+if [ $DIST_TYPES -lt 1 ]; then
+    echo "Choose at least one of --sdist or --wheel"
+    echo ""
+    help
+    exit 1
+fi
+if [ "${VERSION}" == "" ]; then
+    echo "Missing VERSION argument"
+    echo ""
+    help
+    exit 1
+fi
+
+source "${ROOT}/bin/dist-functions"
+if [ -n "${CLEAN}" ]; then
+    echo "Cleaning dist directory ${DIST}"
+    rm -rf "${DIST}" 2> /dev/null
+fi
+
+if [ -n "${SDIST}" ]; then
+    # don't built a wheel for the legacy package
+    # TODO: 6.0 - *actually* remove the legacy package
+    set_metadata_and_setup --sdist --deprecated "neo4j-driver" "${VERSION}" # Legacy package; can be removed in 2.0
+fi
+set_metadata_and_setup "${SETUP_ARGS[@]}" "neo4j" "${VERSION}"
+set_metadata_and_setup "${SETUP_ARGS[@]}" --pwd "$ROOT/pkg_rust" "neo4j-rust-ext" "${VERSION}"
+set_metadata_and_setup "${PY_SETUP_ARGS[@]}" --pwd "$ROOT/pgk_py" "neo4j-py" "${VERSION}"
